version: '3.8'

services:
  # Database Containers
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"

  # Microservices
  order-service:
    build: ./order-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - discovery-service

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"